### ISSUE TITLE
Csound for Android - more controls

### ISSUE THREAD

**Issue by arthunkins** [gogins/csound-android#13]
Would appreciate upping the # of buttons to 8 or preferably 9 (to correspond with the # of sliders). I don't suppose it is possible to visibly associate the buttons with the sliders in a more intuitive way?

**Comment by gogins** [comment]
I can put the buttons to the right or left of the corresponding sliders, is that what you were thinking?

**Comment by gogins** [comment]
Changed to 1 button per slider all on same row, 12 rows in all. The buttons are to the left of the sliders. If there is not enough room to show all 12 rows, you can swipe the panel up and down to see more.
