### ISSUE TITLE
Feature request: Better scroll on Editor tab

### ISSUE THREAD

**Issue by omarcostahamido** [gogins/csound-android#21]
running the available beta release here: https://github.com/gogins/csound-android/releases/tag/v33-beta2

All other tabs behave as expected when scrolling a long window, give it a boost and it keeps scrolling. Not the editor though: it only scrolls when your finger is in touch with the screen. For long files that is... _tiring_.

**Comment by gogins** [comment]
I have made both scrollbar thumbs visible, and increased the `scrollSpeed` of the Ace Editor to 50. That has fixed this for me.
