### ISSUE TITLE
Request inclusion of a few missing opcodes

### ISSUE THREAD

**Issue by ST-Music** [gogins/csound-android#22]
A few newer opcodes (6.17 I think) are not yet included I could really benefit from. Most noticeable are trigexpseg & triglinseg. I do alot of works with trig instr so if possible these would be very beneficial.

Update: the canon. manual example for the trigexpseg was causing crashes. Turns out it was the included Csound default option settings:
-odac 	-d    -m0d     -M0  -+rtmidi=virtual

github don't allow me to delete the issue but consider it resolved.

**Comment by gogins** [comment]
The trinlinseg opcode works for me using the example from the Csound
Reference Manual. I had to modify the Csound options, but it worked fine. I
think most of the newer opcodes are now in the Android build.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by ST-Music** [comment]
Yes, perhaps I should have clarified better. Both opcodes work fine, I just needed to alter the CsOptions as one, not sure which, was causing Csound to crash.

I have not yet found other opcodes that aren't included, quite happy with having access to the newer ones.

I would have deleted the issue but could not, it seems github only allows me to delete my comments within an issue.

**Comment by gogins** [comment]
Close issues, don't delete them.

**Comment by ST-Music** [comment]
Ah, I see now, thank you.
