### ISSUE TITLE
Issues with new editor additions

### ISSUE THREAD

**Issue by ST-Music** [gogins/csound-android#23]
The new horizontal & vertical handles don't work for me. Neither do the copy/paste options. They would be a nice addition. Other than that the newest beta (36) is working extremely well.

**Comment by gogins** [comment]
The handles are not handles, they are "thumbs." I will look into getting
these to be draggable. Copy and paste in the normal Android way works. I
will also look into how that's supposed to work using the editor's context
menu.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
About the scrolling. On Android, one scrolls by touching or clicking on the
scrollbar track. The thumb represents where in the entire document the
visible contents are located. Using the scrollbar in this way works for me.
I will style the scrollbars so that the track is more visible, and add a
note about this in the *User Guide*.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by ST-Music** [comment]
Ok, I understand now. Yes, this works for me, thanks. I was trying to
scroll by clicking on the thumb & dragging. I like the way this is actually
working better - one can touch the track at the bottom, for example, and it
immediately jumps to the bottom of the page.

The one problem now is that when one tries to type on the page & the
keyboard comes up, an opaque section pops up between the keyboard and
scroll track that doesn't allow you to see what you are typing. Attempting
to scroll fails as the keyboard disappears.

I made a screen recording so you can see what I mean. It is hard to see but
I tap to type on line 30 that starts with "k9 = " :

https://www.dropbox.com/scl/fi/4bblkgkuq7kh3ybh0dihy/android_editor.mp4?rlkey=tsnvu7etfd8dli4sphayleu4d&dl=0

In the previous version the opaque section above the keyboard blocking
visibility did not appear, and if I had originally tapped to type on a line
that would subsequently be underneath the keyboard, as soon as the first
letter was typed the page automatically scrolled up to where that line was
visible.

I don't think you really need to make the tracks more visible, they're
quite clearly underneath/beside the thumbs. You might consider making the
thumbs smaller if anything as page visibility on small devices is somewhat
important. I did notice the thumbs, especially the up/down, get smaller as
the page gets larger. Perhaps a fixed size thumb about a quarter/half inch
might be better but I guess this is just personal preference. I'm happy to
use it however it is implemented.

I did however notice that the lower thumb is transparent & the side one is
not - both the thumb & the track block visibility.

**Comment by gogins** [comment]
I've done as much as I think can with these issues. Thanks  @ST-Music  for all your help, which has been most useful.
