### ISSUE TITLE
Req. editor handle removal

### ISSUE THREAD

**Issue by ST-Music** [gogins/csound-android#25]
I know you'd rather be done with this Michael but the new handles have made editing essentially impossible. If one clicks on a lower line, the opaque block created between the lower handle and the keyboard makes it impossible to see what one is typing. 

As this video illustrates, once the keyboard pops up you cannot scroll nor see the characters being typed, you are blind as to what you are trying to edit: 

https://www.dropbox.com/scl/fi/c2eke0quwbg0x8n5va6hz/Scrolling_issue.mp4?rlkey=uls10an1nwbtsfzef9ti8fex1&dl=0

While the handles would have been a nice feature, at least with the previous editor one could at least see what they were editing but this is no longer the case.

**Comment by gogins** [comment]
I think this is not the handles, but the upgraded Ace editor. I will try to
fix this.

**Comment by ST-Music** [comment]
Thanks Michael. No rush, I know this is a long weekend. I found a temp workaround, if I add 20-30 extra blank lines to the end of a csd then I can edit the score etc.
