### ISSUE TITLE
Csound for Android - armeabi-only APK?

### ISSUE THREAD

**Issue by IzzySoft** [gogins/csound-android#5]
Could you please provide an armeabi-v7-only APK? The release just brought the APK size from 24M to 95M (about 4 times the size of the previous version). Your app is currently listed [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.csounds.Csound6), but there's a size limit set to 30M per app which is now exceeded by factor 3, so I had to roll-back this update.

Side note: your release seems to be compiled for debug (`android:debuggable="true"`), which should not be done for releases :wink:

**Comment by gogins** [comment]
Thanks, I'll fix this stuff if I can.

**Comment by IzzySoft** [comment]
Thanks a lot! Just give me a ping when I should check again.

**Comment by gogins** [comment]
Can you use an app bundle? This is a thing that a server such as the Google
Play Store uses to produce APKs specific to the requesting device.

I've added a whole new library for algorithmic composition to the app,
that's the main reason it's bigger. I removed some unneeded files from the
existing APK but it is still too large.

The app bundle itself would be as big as the existing APK but your Web site
may have a different policy, or you can pull device-specific APKs out of
the bundle, or I can do that.

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by IzzySoft** [comment]
Unfortunately no, my repo can only deal with `*.apk` (not with `*.aab`). That's why I asked for an APK with only the armeabi-v7 architecture covered (the libs per arch are about 50M with your APK, reduced in size by packing; thus limiting it to 1 instead of 3 archs might bring it down to 30M – not sure if it really does, though. Give me a sec to try… Ah yuck, no, that only reduces it to around 50M :cry:

But I see e.g. `CsoundAudioProcessor.js` is included multiple times, compressed size close to 10M for each copy:

* `assets/examples/Gogins/js/CsoundAudioProcessor.js`
* `assets/examples/Gogins/CsoundAudioProcessor.js`

The files slightly differ in size, so this might be intended.

Sad. Unless it can be "split" somehow, I'm afraid I cannot hold it. Any plans bringing your app to [F-Droid](https://f-droid.org/) directly, where those size limits do not exist? Or to "modularize" it (as eg keyboard apps do with language modules)?

**Comment by gogins** [comment]
I have changed the release to a signed bundle, which is what I will also
soon be updating both my release and the Google Play Store with.

You may find it possible to pull what you want out of this using bundletool
(https://developer.android.com/studio/command-line/bundletool,
https://github.com/google/bundletool), but as far as I can see, the
individual APKs are still too big for your site, and I don't know how the
user would install these things because they must be installed as a
specific set for a specific device.

I'll take another look at leaving some inessential stuff out, and then
update my release, but I'm not optimistic.

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by IzzySoft** [comment]
Thanks Mike! I cannot ask for more. If it doesn't work out I'd suggest I remove your app from my repo (no good done by keeping an outdated version there). And no, I cannot work with bundles: updates etc are automated, and there's no bundle support with that.

Still, my offer stands: if you wish we can try getting your app (multi-arch) to [F-Droid](https://f-droid.org/). Disclosure: I'm one of the F-Droid maintainers.

**Comment by IzzySoft** [comment]
@gogins as there was no further update: Do you think it's still useful to keep your app in my repo – or would you consider it "obsolete"? If it still works, I can keep the old version, but if not it might be better to remove it.

**Comment by gogins** [comment]
The app is not obsolete, but it is in serious need of maintenance. I will get to that in the coming weeks. Then we can see.

**Comment by IzzySoft** [comment]
That's be great – looking forward to it, thanks!

**Comment by gogins** [comment]
See https://developer.android.com/build/configure-apk-splits. If I can publish an app bundle instead of an .apk file, this should happen for you automatically.

**Comment by gogins** [comment]
I have built an app bundle for Csound for Android. I'll try to get that on the Play Store. If that works, I'll close this issue.

**Comment by gogins** [comment]
It could take some time to convince Google to host this because I don't see any way to avoid using all files permissions, which Google hates. I'm closing this issue.

I am hosting the app, which so far seems to be working fine, as an apk on the release page of this repository. If I can work things out with Google, I will announce that on my blog, to the Csound lists, etc.

**Comment by IzzySoft** [comment]
So no chance for per-ABI APKs here? Guess I then should remove the app [from my repo](https://apt.izzysoft.de/packages/com.csounds.Csound6/): the last release there was 6.14.0 beta from 2020-05-07, so it's more than 3 years old and has no chance to get updated. Per-app limit in my repo is 30 MB. I can make exceptions to a limit, but 90 MB is 3 times over the limit and thus a bit much.

**Comment by IzzySoft** [comment]
@gogins as it seems my last comment didn't reach you: any chance for per-ABI APKs? I'll reset the timer here once more, but otherwise remove the app from my repo in about a month from now, for above mentioned reasons.

**Comment by IzzySoft** [comment]
No chance it seems, so I've just removed your app from my repo. Should you one day provide per-ABI APKs, be welcome to drop me a note and I'll gladly re-establish the listing.
