### ISSUE TITLE
CSound on Android Unresponsive

### ISSUE THREAD

**Issue by Favonias** [gogins/csound-android#6]
After writing [eleven symphonies](https://www.youtube.com/playlist?list=PLSzKpnBM1_465c91Rop0GZ44GynaAHUx7) through CSound on Android, and it's such a great time, my application fails to render and perform a simple tutorial file as, Istvan Varga's, simple fast sine oscillator:

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac    ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o oscils.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1

iflg = p4
asig oscils .7, 220, 0, iflg
     outs asig, asig

endin
</CsInstruments>
<CsScore>

i 1 0 2 0
i 1 3 2 2	;double precision
e
</CsScore>
</CsoundSynthesizer>

What I get is:

CSound is starting...
setCSoundText...

--
CSound 6.16
Android 10

Frontend CSound

**Comment by gogins** [comment]
You have provided just a Csound orchestra. A Csound piece for Csound for Android must be in the form of a CSD file. I changed your example into a CSD file:
```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1

iflg = p4
asig oscils .7, 220, 0, iflg
outs asig, asig

endin
</CsInstruments>
<CsScore>
i 1 0 2 0
i 1 3 2 2 ;double precision
e
</CsScore>
</CsoundSynthesizer>
```
and it ran without a problem.
