### ISSUE TITLE
Csound for Android - rndseed does not appear to work

### ISSUE THREAD

**Issue by ST-Music** [gogins/csound-android#7]
it doesn't turn orange in the included editor and has no effect, for me anyways.

Csound for Android
version code: 30
library version: 6160
Android version 7.0

**Comment by gogins** [comment]
The `rndseed` opcode sets the global random seed only for the `rnd` and `birnd` opcodes. Other random opcodes would not be affected.

**Comment by gogins** [comment]
The coloring of opcodes in the editor is maintained by the [ACE editor team](https://github.com/ajaxorg/ace). You should submit bugs and requests concerning the Csound syntax mode to them.
