### ISSUE TITLE
Csound for Android - pvanal giving error

### ISSUE THREAD

**Issue by ST-Music** [gogins/csound-android#8]
Completes input analysis but states unable to write pvocex file.
![Screenshot_20220902-151508](https://user-images.githubusercontent.com/112670470/188222624-6543ec67-d702-4eb6-8ec2-41d8b0575e34.jpg)
Csound for Android
version code: 30
library version: 6160
Android version 7.0

**Comment by gogins** [comment]
Only certain directories are writable by the Csound for Android app. I will try to provide a minimal working example that does write a pvocex file.

**Comment by ST-Music** [comment]
Hi Michael. FWIW I resolved this issue some time ago but thank you for
addressing it.

instr 1
  aFile   diskin "fox.wav"
  fAnal = pvsanal(aFile, 1024, 256, 1024, 0)
          pvsfwrite fAnal, "/sdcard/Music/Csound/Analysis/mypvs.pvx"
endin

I realize that the ability to choose the path can vary depending on the
Android device used as Art Hunkins pointed out.

Scott

**Comment by gogins** [comment]
That's as I thought! Thanks for getting back to me.
